export const USER_REGISTER = {
  PENDING: 'USER_REGISTER_PENDING',
  SUCCESS: 'USER_REGISTER_SUCCESS',
  FAIL: 'USER_REGISTER_FAIL',
};

export const USER_LOGIN = {
  PENDING: 'USER_LOGIN_PENDING',
  SUCCESS: 'USER_LOGIN_SUCCESS',
  FAIL: 'USER_LOGIN_FAIL',
};

export const USER_VERIFY = {
  PENDING: 'USER_VERIFY_PENDING',
  SUCCESS: 'USER_VERIFY_SUCCESS',
  FAIL: 'USER_VERIFY_FAIL',
};

export const USER_LOGOUT = 'USER_LOGOUT';
